spring.application.name=rule-engine
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

app.jwt.secret=${JWT_SECRET:MinipblRuleEngineSecretKeyForJWTTokenGeneration2026MustBe32BytesLong}
app.jwt.expiration=86400000

spring.profiles.active=${SPRING_PROFILES_ACTIVE:dev}
